### ISSUE TITLE
when i  want to  install CogDL via:git clone git@github.com:THUDM/cogdl.git  , there are some questions

### ISSUE THREAD

**Issue by GorgeousWang** [THUDM/cogdl#137]
## ❓ Questions & Help

Cloning into 'cogdl'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by THINK2TRY** [comment]
You can clone the repository via https instead of ssh.

![image](https://user-images.githubusercontent.com/48679723/103435441-77bb0180-4c49-11eb-86ce-e056ba7eef7e.png)

**Comment by GorgeousWang** [comment]
> You can clone the repository via https instead of ssh.
> 
> ![image](https://user-images.githubusercontent.com/48679723/103435441-77bb0180-4c49-11eb-86ce-e056ba7eef7e.png)

thanks for your answer and what's the next step to update my old release version via cd codgl & pip install -e. 
this is the first time ,that i update my package in this way.

**Comment by THINK2TRY** [comment]
After cloning the repo, just run `pip install -e .` in cogdl directory and cogdl will be installed or updated.

**Comment by GorgeousWang** [comment]
> You can clone the repository via https instead of ssh.
> 
> ![image](https://user-images.githubusercontent.com/48679723/103435441-77bb0180-4c49-11eb-86ce-e056ba7eef7e.png)



> After cloning the repo, just run `pip install -e .` in cogdl directory and cogdl will be installed or updated.
thanks for your answer, it work out.
but i find a problem, in the new example:
from cogdl.tasks import build_task
from cogdl.options import get_default_args

# Get default hyper-parameters for experiments
*
args = get_default_args(task="node_classification", dataset="cora", model="gcn")
# Build and run
task = build_task(args)
ret = task.train()
*
did you set the cuda(my computer isn't supported it) as the default device? because i have a warning information like this:
***
Traceback (most recent call last):
  File "D:/autocogdl/cogdl-master/cogdl-master/Amytest/apiUsage.py", line 8, in <module>
    task = build_task(args)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\__init__.py", line 44, in build_task
    return TASK_REGISTRY[args.task](args)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\base_task.py", line 9, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\node_classification.py", line 119, in __init__
    self.data.apply(lambda x: x.to(self.device))
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\data.py", line 308, in apply
    self[key] = self.__apply__(item, func)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\data\data.py", line 287, in __apply__
    return func(item)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\node_classification.py", line 119, in <lambda>
    self.data.apply(lambda x: x.to(self.device))
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 149, in _lazy_init
    _check_driver()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
****

**Comment by GorgeousWang** [comment]
> After cloning the repo, just run `pip install -e .` in cogdl directory and cogdl will be installed or updated.

and then when i run the new gcn.py example in the unrelease version package, there are some new warning:

Traceback (most recent call last):
  File "D:/autocogdl/cogdl-master/cogdl-master/examples/gcn.py", line 34, in <module>
    task = build_task(args, dataset=dataset, model=model)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\__init__.py", line 49, in build_task
    return TASK_REGISTRY[args.task](args, dataset=dataset, model=model)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\base_task.py", line 9, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\node_classification.py", line 84, in __init__
    super(NodeClassification, self).__init__(args)
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\base_task.py", line 23, in __init__
    self.load_from_checkpoint = args.checkpoint
AttributeError: 'ArgClass' object has no attribute 'checkpoint'
Exception ignored in: <function BaseTask.__del__ at 0x000001E08CF7E828>
Traceback (most recent call last):
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\base_task.py", line 27, in __del__
    self.save_checkpoint()
  File "d:\anaconda3\envs\unleasepackage\cogdl-master\cogdl\tasks\base_task.py", line 42, in save_checkpoint
    if self._checkpoint is not None and issubclass(self.model.__class__, torch.nn.Module):
AttributeError: 'NodeClassification' object has no attribute '_checkpoint'

**Comment by THINK2TRY** [comment]
We will resolve the bugs soon. 
Now you can temporarily run cogdl using command line with "--cpu" set or  add {"checkpoint": False, "cpu": True} in `gcn.py`
