### ISSUE TITLE
"missing 1 required positional argument: num_nodes" when running graphsage model

### ISSUE THREAD

**Issue by AugF** [THUDM/cogdl#14]
I am sorry to bother you, could you help me? when i run the command:
`python scripts/train.py -dt cora --model graphsage -t node_classification`, i get this error:

```
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/gpu/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/xxx/anaconda3/envs/gpu/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/xxx/cogdl/scripts/parallel_train.py", line 34, in main
    result = task.train()
  File "/home/xxx/cogdl/cogdl/tasks/node_classification.py", line 52, in train
    self._train_step()
  File "/home/xxx/cogdl/cogdl/tasks/node_classification.py", line 80, in _train_step
    self.model(self.data.x, self.data.edge_index)[self.data.train_mask],
  File "/home/xxx/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/cogdl/cogdl/models/nn/graphsage.py", line 86, in forward
    x = self.convs[i](x, edge_index_sp)
  File "/home/xxx/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'num_nodes'
```

**Comment by cenyk1230** [comment]
Hi @AugF,

Sorry for the late reply. We have fixed this bug. Please let me know if you need any help.

Thanks
