### ISSUE TITLE
cogdl on linux tesla K40c

### ISSUE THREAD

**Issue by rain0831** [THUDM/cogdl#26]
HI, my environment is linux, tesla K40c, pytorch1.4, cuda101, python3.7.
When I run python gcn.py, the error information is 
Traceback (most recent call last):
  File "gcn.py", line 29, in <module>
    task = build_task(args, dataset=dataset, model=model)
  File "/home/hsc/Desktop/wyt/cogdl-master/cogdl/tasks/__init__.py", line 54, in build_task
    return TASK_REGISTRY[args.task](args, dataset=dataset, model=model)
  File "/home/hsc/Desktop/wyt/cogdl-master/cogdl/tasks/node_classification.py", line 35, in __init__
    args.num_features = dataset.num_features
  File "/home/hsc/Desktop/wyt/anaconda3/envs/pytorch_1.4/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 117, in num_features
    return self.num_node_features
  File "/home/hsc/Desktop/wyt/anaconda3/envs/pytorch_1.4/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 112, in num_node_features
    return self[0].num_node_features
  File "/home/hsc/Desktop/wyt/anaconda3/envs/pytorch_1.4/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 189, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/home/hsc/Desktop/wyt/anaconda3/envs/pytorch_1.4/lib/python3.7/site-packages/torch_geometric/transforms/target_indegree.py", line 27, in __call__
    deg = degree(col, data.num_nodes)
  File "/home/hsc/Desktop/wyt/anaconda3/envs/pytorch_1.4/lib/python3.7/site-packages/torch_geometric/utils/degree.py", line 20, in degree
    out = torch.zeros((num_nodes), dtype=dtype, device=index.device)
RuntimeError: CUDA error: no kernel image is available for execution on the device

K40c  has a compute capability of 3.5. Does it not support PyTorch 1.4?
Thanks!

**Comment by cenyk1230** [comment]
Hi @wuyutongsusan,

Thank you for your attention. Please refer to the issue of PyTorch, such as https://github.com/pytorch/pytorch/issues/31285. It seems that you should build PyTorch from the source because PyTorch binaries are compiled only for arch 3.7 or newer.
