### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" when using customed graph classificaion dataset

### ISSUE THREAD

**Issue by omitedy** [THUDM/cogdl#324]
## ❓ Questions & Help

你好，我在 jupyter 环境中自定义图分类数据集的时候遇到一个问题，在实例化图分类数据集的时候，读取缓存的 `subgraph.pt` 时，报错 `TypeError: 'NoneType' object is not subscriptable`。在命令行中运行时会有 `warning` 提示编译器版本不一致，但是我尝试了文档中自定义数据集中的原始代码是没有问题的。感觉是在存储或者读取 `.pt` 文件时出现了错误，导致没有存储成功或者读取成功？

出问题的代码如下：
```
import torch
import json
from cogdl.data import Graph
from cogdl.datasets import GraphDataset
from cogdl.experiments import experiment
import random

class MyGraphDataset(GraphDataset):
    def __init__(self, path="subgraph.pt"):
        self.path = path
        super(MyGraphDataset, self).__init__(path, metric="accuracy")

    def process(self):
        # Load and preprocess data
        with open("graphs_feature.json", 'r') as f:
            graphs_dict = json.load(f)
        
        # Here we randomly generate several graphs for simplicity as an example
        graphs = []
        for graph in graphs_dict:
            x = torch.tensor(graph['x'])
            y = torch.tensor(graph['y'])
            edges = torch.tensor(graph['edges'])
            graphs.append(Graph(x=x, edge_index=edges, y=y))
        return graphs

if __name__ == "__main__":
    dataset = MyGraphDataset()
    experiment(model="gin", dataset=dataset, logger="tensorboard", 
                   hidden_size=256, num_layers=3, dropout=0.1, 
                   num_mlp_layers=3)
```
报错信息如下：
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_47341/3360418470.py in <module>
     26 
     27 if __name__ == "__main__":
---> 28     dataset = MyGraphDataset()
     29     experiment(model="gin", dataset=dataset, logger="tensorboard", 
     30                    hidden_size=256, num_layers=3, dropout=0.1,

/tmp/ipykernel_47341/3360418470.py in __init__(self, path)
      9     def __init__(self, path="subgraph.pt"):
     10         self.path = path
---> 11         super(MyGraphDataset, self).__init__(path, metric="accuracy")
     12 
     13     def process(self):

/home/ubuntu/anaconda3/envs/cogdl/lib/python3.7/site-packages/cogdl/datasets/customized_data.py in __init__(self, path, metric)
    117         # try:
    118         data = torch.load(path)
--> 119         if hasattr(data[0], "y") and data[0].y is None:
    120             self.y = torch.cat([idata.y for idata in data])
    121         self.data = data

TypeError: 'NoneType' object is not subscriptable
```
 另外我在使用命令行运行该段代码的时候报错信息如下：
```
❯ python gc.py                                                                                                                                                     
/home/ubuntu/anaconda3/envs/cogdl/lib/python3.7/site-packages/torch/utils/cpp_extension.py:323: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++ 4.9.3) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Traceback (most recent call last):
  File "gc.py", line 28, in <module>
    dataset = MyGraphDataset()
  File "gc.py", line 11, in __init__
    super(MyGraphDataset, self).__init__(path, metric="accuracy")
  File "/home/ubuntu/anaconda3/envs/cogdl/lib/python3.7/site-packages/cogdl/datasets/customized_data.py", line 119, in __init__
    if hasattr(data[0], "y") and data[0].y is None:
TypeError: 'NoneType' object is not subscriptable

```
我的系统和环境信息如下：
```
❯ uname -a 
Linux server 4.15.0-139-generic #143~16.04.1-Ubuntu SMP Wed Mar 17 08:10:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
❯ pip list | grep cogdl
cogdl                             0.5.2
❯ python -V
Python 3.7.11
```

**Comment by omitedy** [comment]
数据处理问题，导致数据没有存储成功
