### ISSUE TITLE
使用自定义数据集来进行图分类任务

### ISSUE THREAD

**Issue by zhanghaoxuan184** [THUDM/cogdl#390]
## ❓ Questions & Help

当我使用自定义数据集来进行图分类任务时，会出现以下错误，并且我不太理解60121这个数字是怎样计算出来的

Traceback (most recent call last):
  File "D:/cogdl-master/myData.py", line 92, in <module>
    experiment(model="gin", dataset=dataset ,epochs = 100 ,hidden_size=16)
  File "D:\cogdl-master\cogdl\experiments.py", line 360, in experiment
    return raw_experiment(args)
  File "D:\cogdl-master\cogdl\experiments.py", line 264, in raw_experiment
    results = [train(args) for args in variant_args_generator(args, variants)]
  File "D:\cogdl-master\cogdl\experiments.py", line 264, in <listcomp>
    results = [train(args) for args in variant_args_generator(args, variants)]
  File "D:\cogdl-master\cogdl\experiments.py", line 144, in train
    dataset_wrapper = dw_class(dataset, **data_wrapper_args)
  File "D:\cogdl-master\cogdl\wrappers\data_wrapper\graph_classification\graph_classification_dw.py", line 27, in __init__
    self.setup_node_features()
  File "D:\cogdl-master\cogdl\wrappers\data_wrapper\graph_classification\graph_classification_dw.py", line 41, in setup_node_features
    self.dataset.data = node_degree_as_feature(self.dataset.data)
  File "D:\cogdl-master\cogdl\wrappers\tools\wrapper_utils.py", line 95, in node_degree_as_feature
    deg = graph.degrees().long()
  File "D:\cogdl-master\cogdl\data\data.py", line 691, in degrees
    return self._adj.degrees()
  File "D:\cogdl-master\cogdl\data\data.py", line 303, in degrees
    return get_degrees(self.row, self.col, num_nodes=self.num_nodes)
  File "D:\cogdl-master\cogdl\utils\graph_utils.py", line 16, in get_degrees
    degrees = out.scatter_add_(dim=0, index=row, src=b)
RuntimeError: index -24 is out of bounds for dimension 0 with size 60121

Process finished with exit code 1

其中process部分代码为：
    def process(self):
        # Load and preprocess data
        # Here we randomly generate several graphs for simplicity as an example

        l=[1,2,3,4,5,6,7,8]
        graphs = []
        num = 0

       #grd_read这个函数的返回值是一个torch.LongTensor维度是2*31444

        for i in range(1024):
            edges = grd_read(list[i])

            if i%128==0 and i!=0:
                num=num+1
                label = torch.LongTensor(np.array(l[num]))
            else:
                label = torch.LongTensor(np.array(l[num]))
            if num == 7:
                num = 0

            graphs.append(Graph(edge_index=edges, y=label))
        return graphs

下面是一些变量的值：
__exception__ = {tuple: 3} (<class 'RuntimeError'>, RuntimeError('index -24 is out of bounds for dimension 0 with size 60121'), <traceback object at 0x000001B165E32D80>)
b = {Tensor: 31444} tensor([1., 1., 1.,  ..., 1., 1., 1.])
col = {Tensor: 31444} tensor([ -169,    -3,    -7,  ..., 47536, 48430, 49306])
device = {device} cpu
num_nodes = {int} 60121
out = {Tensor: 60121} tensor([0., 0., 0.,  ..., 0., 0., 0.])
row = {Tensor: 31444} tensor([10000,  9969,  9932,  ..., 60114, 60116, 60118])

**Comment by QingFei1** [comment]
你好，col和row组成edge_index，60121是节点的数量，是取row和col的最大值+1得到的。应该是自定义数据集出错了或者是数据集出错，这里看你的结果col值存在负数，这个应该是报错的原因。

**Comment by zhanghaoxuan184** [comment]
好的，还想问一下GRAPH（edges，label）函数是怎样把一个矩阵转换成图的啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月07日 16:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [THUDM/cogdl] 使用自定义数据集来进行图分类任务 (Issue #390) |

你好，col和row组成edge_index，60121是节点的数量，是取row和col的最大值+1得到的。应该是自定义数据集出错了或者是数据集出错，这里看你的结果col值存在负数，这个应该是报错的原因。

**Comment by zhanghaoxuan184** [comment]
好的，非常感谢您的回复，还想问一下Graph(edge_index=edges, y=label)这个函数是怎么把输入的矩阵变成图数据结构的？

**Comment by QingFei1** [comment]
我们在CogDL中使用cogdl.data.Graph对象来表示一张图，你可以看看我们的[文档](https://docs.cogdl.ai/en/latest/index.html)

**Comment by zhanghaoxuan184** [comment]
好的，再次感谢！

**Comment by QingFei1** [comment]
不客气！

**Comment by zhanghaoxuan184** [comment]
我在对数据集进行筛查以后，应该是数据有负值产生的问题，于是我将负值都改为正值，报出了以下的错误：
请问是我的内存不够了吗？还有就是运行到这一步的话是不是说明已经解决了上面我提到的问题？

|---------------------------------------------------------------------------------------------|
    *** Running (`data.pt`, `gin`, `graph_classification_dw`, `graph_classification_mw`)
|---------------------------------------------------------------------------------------------|
Traceback (most recent call last):
  File "D:/cogdl-master/myData.py", line 92, in <module>
    experiment(model="gin", dataset=dataset ,epochs = 100 ,hidden_size=16, batch_size=1)
  File "D:\cogdl-master\cogdl\experiments.py", line 360, in experiment
    return raw_experiment(args)
  File "D:\cogdl-master\cogdl\experiments.py", line 264, in raw_experiment
    results = [train(args) for args in variant_args_generator(args, variants)]
  File "D:\cogdl-master\cogdl\experiments.py", line 264, in <listcomp>
    results = [train(args) for args in variant_args_generator(args, variants)]
  File "D:\cogdl-master\cogdl\experiments.py", line 171, in train
    model = build_model(args)
  File "D:\cogdl-master\cogdl\models\__init__.py", line 43, in build_model
    return getattr(module, class_name).build_model_from_args(args)
  File "D:\cogdl-master\cogdl\models\nn\gin.py", line 46, in build_model_from_args
    return cls(
  File "D:\cogdl-master\cogdl\models\nn\gin.py", line 89, in __init__
    self.linear_prediction.append(nn.Linear(in_feats, out_feats))
  File "C:\Users\Administrator\Anaconda\envs\pytorch_gpu\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: Storage size calculation overflowed with sizes=[7578771155443791419, 148]

Process finished with exit code 1
