### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by yizhihenpidehou** [THUDM/cogdl#426]
## Environment

* OS: mac os 12.5 (21G72)
* Python version: 3.9
* PyTorch version: 2.0.0
* CUDA/cuDNN version: none
* How did you try to install CogDL (wheel, source): wheel
* Any other relevant information:

## Checklist

- [yes ] I followed the [installation guide](https://github.com/thudm/cogdl#requirements-and-installation).
- [ I do not have CUDA in my MacBook pro] I set up CUDA correctly.
- [ No] I do have multiple CUDA versions on my machine.
Error information:
>>> import subprocess
>>> subprocess.check_output(["hipconfig", "--rocmpath"])

## Additional context

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
>>> import cogdl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/__init__.py", line 3, in <module>
    from .experiments import experiment
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/experiments.py", line 15, in <module>
    from cogdl.utils import set_random_seed, tabulate_results
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/utils/__init__.py", line 1, in <module>
    from .utils import *
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/utils/utils.py", line 16, in <module>
    from .graph_utils import coo2csr_index
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/utils/graph_utils.py", line 7, in <module>
    from cogdl.operators.sample import coo2csr_cpu, coo2csr_cpu_index
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/cogdl/operators/sample.py", line 2, in <module>
    from torch.utils.cpp_extension import load
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/yizhihenpidehou/miniconda3/envs/env_eg/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'

**Comment by cenyk1230** [comment]
Hi @yizhihenpidehou ,

抱歉，我们没有对mac os做深入的测试。不知道你能否新建一个PyTorch 1.x的环境再尝试一下，看起来是PyTorch的问题。
