### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'train_mask'

### ISSUE THREAD

**Issue by Song-xx** [THUDM/CogDL#432]
## ❓ Questions & Help

I am using unsup_graphsage to train on cora dataset. This error happens.

my enviroment is:

cogdl==0.6.0
macos m1
python=3.9

the error message is :
```bash
Traceback (most recent call last):
  ......
  File "/Users/xxx/python3.9/site-packages/cogdl/pipelines.py", line 204, in __call__
    model = train(self.args)
  File "/Users/xxx/python3.9/site-packages/cogdl/experiments.py", line 147, in train
    dataset_wrapper = dw_class(dataset, **data_wrapper_args)
  File "/Users/xxx/python3.9/site-packages/cogdl/wrappers/data_wrapper/node_classification/unsup_graphsage_dw.py", line 18, in __init__
    dataset, sizes=sample_size, batch_size=batch_size, mask=dataset.data.train_mask
AttributeError: 'Graph' object has no attribute 'train_mask'
```
The problem code lies in:
```python
class UnsupGraphSAGEDataWrapper(DataWrapper):
    @staticmethod
    def add_args(parser):
        # fmt: off
        parser.add_argument("--batch-size", type=int, default=128)
        parser.add_argument("--sample-size", type=int, nargs='+', default=[10, 10])
        # fmt: on

    def __init__(self, dataset, batch_size: int, sample_size: list):
        super(UnsupGraphSAGEDataWrapper, self).__init__(dataset)
        self.dataset = dataset
        self.train_dataset = UnsupNeighborSamplerDataset(
            dataset, sizes=sample_size, batch_size=batch_size, mask=dataset.data.train_mask
        )
        self.val_dataset = UnsupNeighborSamplerDataset(
            dataset, sizes=sample_size, batch_size=batch_size * 2, mask=dataset.data.val_mask
        )
        self.test_dataset = UnsupNeighborSamplerDataset(
            dataset=self.dataset,
            mask=None,
            sizes=[-1],
            batch_size=batch_size * 2,
        )
        self.x = self.dataset.data.x
        self.y = self.dataset.data.y
        self.batch_size = batch_size
        self.sample_size = sample_size
```
I tried to find a solution but failed. Any one can help me ? thx

**Comment by cenyk1230** [comment]
Hi @Song-xx ,

Could you please give the exact code/script for reproducing the error? Do you use `experiment` or `pipeline` or other APIs?

**Comment by Song-xx** [comment]
> 

I juse use the pipeline by 'from cogdl import pipeline'. The code I use is similar to these in the tutorial:

```python3
data = build_dataset_from_name('cora').data
edge_index = np.array([[x, y] for x, y in zip(
    data.edge_index[0].tolist(), data.edge_index[1].tolist())])
generator = pipeline("generate-emb", model='unsup_graphsage', return_model=True,
                     num_features=-1, hidden_size=emb_dim, cpu=True,
                     cpu_inference=True, no_test=True)
emb = generator(edge_index, data.x.numpy())
```
