### ISSUE TITLE
python scripts/train.py --task node_classification --dataset cora --model gcn

### ISSUE THREAD

**Issue by happywei** [THUDM/cogdl#46]
python scripts/train.py --task node_classification --dataset cora --model gcn

Using backend: pytorch
Namespace(cpu=False, dataset=['cora'], device_id=[0], dropout=0.5, enhance=None, hidden_size=64, lr=0.01, max_epoch=500, model=['gcn'], num_classes=None, num_features=None, patience=100, save_dir='.', seed=[1], task='node_classification', weight_decay=0.0005)
Traceback (most recent call last):
  File "scripts/train.py", line 101, in <module>
    results = [main(args) for args in variant_args_generator(args, variants)]
  File "scripts/train.py", line 101, in <listcomp>
    results = [main(args) for args in variant_args_generator(args, variants)]
  File "scripts/train.py", line 29, in main
    task = build_task(args)
  File "/Users/happywei/Desktop/code/cogdl-master/cogdl/tasks/__init__.py", line 49, in build_task
    return TASK_REGISTRY[args.task](args)
  File "/Users/happywei/Desktop/code/cogdl-master/cogdl/tasks/node_classification.py", line 66, in __init__
    self.data.apply(lambda x: x.to(self.device))
  File "/Users/happywei/opt/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 308, in apply
    self[key] = self.__apply__(item, func)
  File "/Users/happywei/opt/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 287, in __apply__
    return func(item)
  File "/Users/happywei/Desktop/code/cogdl-master/cogdl/tasks/node_classification.py", line 66, in <lambda>
    self.data.apply(lambda x: x.to(self.device))
  File "/Users/happywei/opt/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 186, in _lazy_init
    _check_driver()
  File "/Users/happywei/opt/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

我配置的环境是基于CPU版本的PyTorch 1.6，请问只有配置CUDA才能运行吗？

**Comment by cenyk1230** [comment]
@happywei,

Thank you for your interest in our CogDL. You need to add the argument `--cpu` to use CPU for model training. My apologies for not mentioning it in the README.

**Comment by happywei** [comment]
> @happywei,
> 
> Thank you for your interest in our CogDL. You need to add the argument `--cpu` to use CPU for model training. My apologies for not mentioning it in the README.

copy that, thanks~

**Comment by happywei** [comment]
thanks~
